import type { ClauseRecord } from '../types';

const OUTPUTS: ClauseRecord['linkedOutputTypes'] = [
  'summary_support',
  'sources_library',
  'report_body',
  'report_appendix',
  'draft_context',
];

function notes(designer: string, builder: string, developer: string, reviewer: string) {
  return { designer, builder, developer, reviewer };
}

type ClauseSeed = Omit<ClauseRecord, 'id' | 'projectId' | 'documentId' | 'documentType' | 'createdAt' | 'updatedAt'> & {
  slug: string;
};

const CALCASIEU_DEMO_SEED: ClauseSeed[] = [
  {
    slug: 'document-precedence',
    sectionRef: 'Section 3.02(b)',
    pageRef: 'Agreement p.3 / PDF p.12',
    title: 'Contract document order of precedence',
    clauseFamily: 'hierarchy',
    clauseSubtype: 'document_precedence',
    excerpt: 'The contract documents are interpreted in a defined order, with the agreement, approved ATCs, technical provisions, and proposal each carrying a specified place in the stack.',
    plainEnglishMeaning: 'When two contract sources conflict, the agreement provides a priority order instead of leaving the issue open-ended.',
    whyItMatters: 'This is the first clause to test when review comments point to a requirement different from what the design team expected.',
    triggerConditions: ['Conflicting contract provisions', 'Reviewer cites a different source than the design team'],
    linkedIssueTypes: ['conflict-in-criteria', 'mixed-issue', 'unclear'],
    linkedDeadlineTypes: ['dispute_escalation_review'],
    linkedOutputTypes: OUTPUTS,
    perspectiveNotes: notes(
      'Confirm the controlling document before pushing back on a comment.',
      'Use it to see whether downstream cost exposure still sits inside baseline scope.',
      'This helps separate interpretation fights from owner-driven changes.',
      'It provides the clean hierarchy rule for deciding which source governs.'
    ),
    confidence: 'High',
    tags: ['hierarchy', 'precedence', 'conflict'],
  },
  {
    slug: 'higher-standard-control',
    sectionRef: 'Section 3.02(c)',
    pageRef: 'Agreement p.3 / PDF p.12',
    title: 'Higher-standard and more stringent requirement control',
    clauseFamily: 'hierarchy',
    clauseSubtype: 'higher_standard_control',
    excerpt: 'Where different standards apply to the same subject, the higher quality or more stringent requirement determined by LA DOTD will prevail unless LA DOTD approves otherwise in writing.',
    plainEnglishMeaning: 'If two standards both apply, LA DOTD can enforce the tougher one.',
    whyItMatters: 'This is a common owner-side basis for rejecting a design-builder argument that a lower standard should control.',
    triggerConditions: ['Competing standards', 'Reviewer insists on stricter criteria'],
    linkedIssueTypes: ['conflict-in-criteria', 'stricter-standard-enforcement'],
    linkedDeadlineTypes: ['dispute_escalation_review'],
    linkedOutputTypes: OUTPUTS,
    perspectiveNotes: notes(
      'Expect tougher cited criteria to win unless LA DOTD backs off in writing.',
      'This can move cost and sequencing if the stricter interpretation controls.',
      'It weakens arguments that a lower baseline standard should govern.',
      'Use it when the review comment points to the more conservative requirement.'
    ),
    confidence: 'High',
    tags: ['higher-standard', 'stricter', 'criteria'],
  },
  {
    slug: 'proposal-commitment-binding',
    sectionRef: 'Section 3.02(d)',
    pageRef: 'Agreement p.3 / PDF p.12',
    title: 'Proposal commitments become binding scope',
    clauseFamily: 'hierarchy',
    clauseSubtype: 'proposal_commitment_binding',
    excerpt: 'If the proposal offers higher quality items, additional services, or terms more advantageous to LA DOTD, the developer must comply with those proposal statements and designs.',
    plainEnglishMeaning: 'A better promise in the proposal can become binding even if the base specs say less.',
    whyItMatters: 'This can erase what looks like a change claim if the developer already promised the higher standard in its proposal.',
    triggerConditions: ['Reviewer cites proposal promise', 'Design-builder says comment is beyond base specs'],
    linkedIssueTypes: ['design-correction', 'stricter-standard-enforcement', 'mixed-issue'],
    linkedDeadlineTypes: ['dispute_escalation_review'],
    linkedOutputTypes: OUTPUTS,
    perspectiveNotes: notes(
      'Check proposal language before saying the owner added new scope.',
      'Proposal-driven quality promises can create real cost exposure.',
      'This is a strong defense to later extra-compensation arguments.',
      'It links rejection comments back to bidder commitments.'
    ),
    confidence: 'High',
    tags: ['proposal', 'binding', 'commitment'],
  },
  {
    slug: 'submittal-review-window',
    sectionRef: 'Section 10.05(b)(i)',
    pageRef: 'Agreement p.56 / PDF p.65',
    title: 'LA DOTD standard submittal review window',
    clauseFamily: 'submittal_review',
    clauseSubtype: 'submittal_review_window',
    excerpt: 'LA DOTD typically has 14 days to review and comment on or approve a complete submittal unless another contract provision sets a different period.',
    plainEnglishMeaning: 'A clean submittal starts a defined review clock.',
    whyItMatters: 'This is the anchor clause for deciding whether review timing actually slipped or the package was still within the agreed review window.',
    triggerConditions: ['Review timing dispute', 'Submittal status follow-up'],
    linkedIssueTypes: ['incomplete-submittal', 'delay-risk', 'agency-interpretation-shift'],
    linkedDeadlineTypes: ['submittal_review_followup'],
    linkedOutputTypes: OUTPUTS,
    perspectiveNotes: notes(
      'Track the contract review clock, not just informal expectations.',
      'This affects release timing and downstream field sequencing.',
      'It separates late review from incomplete submission problems.',
      'Use it as the baseline timing rule for submittal disputes.'
    ),
    confidence: 'High',
    tags: ['submittal', 'review-window', 'timing'],
  },
  {
    slug: 'incomplete-submittal-return',
    sectionRef: 'Section 10.05(b)(ii)',
    pageRef: 'Agreement p.56 / PDF p.65',
    title: 'Incomplete or inaccurate submittals can be returned',
    clauseFamily: 'submittal_review',
    clauseSubtype: 'incomplete_submittal_return',
    excerpt: 'LA DOTD may return inaccurate or incomplete submittals within seven days and require revision before continuing the review path.',
    plainEnglishMeaning: 'An incomplete package can be bounced early instead of running the normal review clock.',
    whyItMatters: 'This is one of the strongest procedural answers when the team says the owner sat too long on a bad package.',
    triggerConditions: ['Rejected as incomplete', 'Reviewer says package lacked required content'],
    linkedIssueTypes: ['incomplete-submittal', 'delay-risk'],
    linkedDeadlineTypes: ['submittal_review_followup'],
    linkedOutputTypes: OUTPUTS,
    perspectiveNotes: notes(
      'If the package was thin, this clause weakens any late-review argument.',
      'Incomplete submittals can create internal rework without owner liability.',
      'This is the first defense to a missed-review-window complaint.',
      'It gives reviewers explicit authority to bounce deficient packages quickly.'
    ),
    confidence: 'High',
    tags: ['submittal', 'incomplete', 'return'],
  },
  {
    slug: 'review-clock-rule',
    sectionRef: 'Section 10.05(d)',
    pageRef: 'Agreement p.57 / PDF p.66',
    title: 'Silence is not substantive approval',
    clauseFamily: 'submittal_review',
    clauseSubtype: 'review_clock_rule',
    excerpt: 'If LA DOTD gives no comments within the review period, the developer may proceed at its election and risk, and late comments alone do not create a delay or compensation claim.',
    plainEnglishMeaning: 'No comments does not mean the owner guaranteed compliance.',
    whyItMatters: 'This blocks attempts to convert silence into automatic approval or a clean damages claim.',
    triggerConditions: ['No comments received', 'Later comments after team already proceeded'],
    linkedIssueTypes: ['agency-interpretation-shift', 'delay-risk', 'mixed-issue'],
    linkedDeadlineTypes: ['submittal_review_followup'],
    linkedOutputTypes: OUTPUTS,
    perspectiveNotes: notes(
      'Proceeding after silence still carries design risk.',
      'This makes silent review periods less useful as a damages hook.',
      'It weakens the argument that later comments are automatically barred.',
      'Use it when the team is relying too heavily on owner silence.'
    ),
    confidence: 'High',
    tags: ['submittal', 'silence', 'risk'],
  },
  {
    slug: 'review-nonreliance',
    sectionRef: 'Section 10.06(a)',
    pageRef: 'Agreement p.58 / PDF p.67',
    title: 'LA DOTD review and oversight are not reliance rights',
    clauseFamily: 'anti_reliance',
    clauseSubtype: 'review_nonreliance',
    excerpt: 'LA DOTD review, comment, approval, and oversight rights exist solely for LA DOTD’s protection and may not be relied on by the developer as a defense to its own obligations.',
    plainEnglishMeaning: 'Owner review is not a warranty that the design-builder is right.',
    whyItMatters: 'This is the core clause that undercuts “they reviewed it, so we relied on it” arguments.',
    triggerConditions: ['Reliance on approval', 'Owner reviewed but later objected'],
    linkedIssueTypes: ['design-correction', 'agency-interpretation-shift', 'conflict-in-criteria'],
    linkedDeadlineTypes: ['dispute_escalation_review'],
    linkedOutputTypes: OUTPUTS,
    perspectiveNotes: notes(
      'Do not assume owner review shifts core design responsibility away from the team.',
      'This protects the owner even when oversight was active.',
      'It is a strong response to reliance-based compensation narratives.',
      'Use it to explain why oversight is not a duty of care to the developer.'
    ),
    confidence: 'High',
    tags: ['anti-reliance', 'review', 'oversight'],
  },
  {
    slug: 'approval-nonwaiver',
    sectionRef: 'Section 10.06(c)',
    pageRef: 'Agreement p.59 / PDF p.68',
    title: 'Approvals and acceptance do not waive developer responsibility',
    clauseFamily: 'anti_reliance',
    clauseSubtype: 'approval_nonwaiver',
    excerpt: 'No LA DOTD review right, approval, acceptance, or final acceptance relieves the developer of performance obligations, waives LA DOTD remedies, or creates an implied representation or warranty.',
    plainEnglishMeaning: 'Even approved work can still be the developer’s responsibility.',
    whyItMatters: 'This preserves correction rights even after prior approvals or acceptance milestones.',
    triggerConditions: ['Earlier approval cited as defense', 'Accepted package later challenged'],
    linkedIssueTypes: ['design-correction', 'conflict-in-criteria', 'unclear'],
    linkedDeadlineTypes: ['dispute_escalation_review'],
    linkedOutputTypes: OUTPUTS,
    perspectiveNotes: notes(
      'Prior approval is not permanent sign-off on design risk.',
      'This keeps later correction exposure alive after earlier acceptance.',
      'It distinguishes administrative approval from liability allocation.',
      'Use it when a party overstates the effect of earlier approvals.'
    ),
    confidence: 'High',
    tags: ['anti-reliance', 'approval', 'non-waiver'],
  },
  {
    slug: 'delay-event-notice',
    sectionRef: 'Section 12.01(a)',
    pageRef: 'Agreement p.65 / PDF p.74',
    title: 'Delay Event notice and waiver timing',
    clauseFamily: 'delay_events',
    clauseSubtype: 'delay_event_notice',
    excerpt: 'Delay Event notice must be given promptly; relief before the notice date can be waived if notice is late, and failure to give notice within thirty days can bar relief entirely.',
    plainEnglishMeaning: 'Time relief lives or dies on fast notice.',
    whyItMatters: 'This is the first procedural gatekeeper for any schedule-extension position.',
    triggerConditions: ['Delay claim', 'Schedule extension request', 'Late notice concern'],
    linkedIssueTypes: ['delay-risk', 'mixed-issue'],
    linkedDeadlineTypes: ['delay_event_notice_review', 'delay_claim_due'],
    linkedOutputTypes: OUTPUTS,
    perspectiveNotes: notes(
      'Check this notice clock before building a delay narrative.',
      'Late notice can kill recovery even if the delay is real.',
      'It is usually the owner’s first procedural answer to time relief.',
      'Use it to surface waiver risk early in the review.'
    ),
    confidence: 'High',
    tags: ['delay', 'notice', 'waiver'],
  },
  {
    slug: 'compensation-event-notice',
    sectionRef: 'Section 13.01(a)-(b)',
    pageRef: 'Agreement pp.68-69 / PDF pp.77-78',
    title: 'Compensation Event notice, claim, and waiver timing',
    clauseFamily: 'compensation_events',
    clauseSubtype: 'compensation_event_notice',
    excerpt: 'A Compensation Event notice must be delivered promptly, with limited relief if late and no relief if notice is not given within thirty days; the developer then must submit a written claim with facts, damages, and calculations on the contract timetable.',
    plainEnglishMeaning: 'Money relief requires both a timely notice and a timely supported claim.',
    whyItMatters: 'This is the commercial equivalent of the delay notice rule and a major risk for any extra-compensation posture.',
    triggerConditions: ['Extra compensation request', 'Damages claim', 'Late cost notice'],
    linkedIssueTypes: ['compensation-risk', 'owner-driven-change'],
    linkedDeadlineTypes: ['compensation_notice_review', 'compensation_claim_due'],
    linkedOutputTypes: OUTPUTS,
    perspectiveNotes: notes(
      'Do not wait for perfect pricing before preserving the claim timeline.',
      'Commercial recovery can shrink fast if the paperwork lags.',
      'This is a strong owner-side procedural defense to cost claims.',
      'Use it to assess whether the claim file is timely enough to matter.'
    ),
    confidence: 'High',
    tags: ['compensation', 'notice', 'claim'],
  },
  {
    slug: 'request-for-change-proposal',
    sectionRef: 'Section 13.02(b)-(c)',
    pageRef: 'Agreement pp.74-75 / PDF pp.83-84',
    title: 'Request for Change Proposal and Change Order path',
    clauseFamily: 'ladot_changes',
    clauseSubtype: 'request_for_change_proposal',
    excerpt: 'If LA DOTD wants to initiate a change, it issues a Request for Change Proposal, the developer responds with impacts and pricing, and the work is normally performed after a mutually agreed Change Order.',
    plainEnglishMeaning: 'Owner-driven change should move through a defined proposal-and-change-order process.',
    whyItMatters: 'This is the clean contractual path when comments or direction start to look like a real scope shift.',
    triggerConditions: ['Owner-driven scope shift', 'Request for pricing or schedule impact'],
    linkedIssueTypes: ['owner-driven-change', 'directive-candidate', 'mixed-issue'],
    linkedDeadlineTypes: ['directive_followup', 'pricing_support_request_due'],
    linkedOutputTypes: OUTPUTS,
    perspectiveNotes: notes(
      'If the comment really changes scope, push it into this path.',
      'This creates the commercial paper trail before changed work is absorbed.',
      'Use it to separate correction work from owner-initiated change.',
      'It frames how LA DOTD should formalize requested scope growth.'
    ),
    confidence: 'High',
    tags: ['change', 'rfcp', 'change-order'],
  },
  {
    slug: 'directive-letter',
    sectionRef: 'Section 13.02(d)-(e)',
    pageRef: 'Agreement p.76 / PDF p.85',
    title: 'Directive Letter and proceed-while-disputed path',
    clauseFamily: 'directive',
    clauseSubtype: 'directive_letter',
    excerpt: 'LA DOTD may issue a Directive Letter if it wants work to proceed or if there is a dispute over scope, the developer performs as directed, and the commercial terms are later memorialized through a Change Order or dispute resolution.',
    plainEnglishMeaning: 'Proceed now, preserve the fight, and true-up later.',
    whyItMatters: 'This is the core clause for reservation-of-rights and request-for-direction language when stopping work is not realistic.',
    triggerConditions: ['Disputed direction', 'Owner wants work to proceed now', 'Need reservation of rights'],
    linkedIssueTypes: ['directive-candidate', 'owner-driven-change'],
    linkedDeadlineTypes: ['directive_followup', 'dispute_escalation_review'],
    linkedOutputTypes: OUTPUTS,
    perspectiveNotes: notes(
      'Use this when the team needs formal direction but cannot stop work.',
      'It supports proceed-while-disputed with commercial tracking intact.',
      'This is the right frame for reservation-of-rights language.',
      'It gives LA DOTD a formal proceed-now mechanism.'
    ),
    confidence: 'High',
    tags: ['directive', 'proceed', 'reservation-of-rights'],
  },
  {
    slug: 'subcontract-pricing-documents',
    sectionRef: 'Section 17.11',
    pageRef: 'Agreement p.95 / PDF p.104',
    title: 'Subcontract and consultant pricing documents must be preserved',
    clauseFamily: 'pricing_support',
    clauseSubtype: 'subcontract_pricing_documents',
    excerpt: 'The developer must require the design-build contractor, O&M contractor, lead designer, toll system provider, and tolling operator to preserve and provide the documentary information used to set subcontract pricing and change pricing.',
    plainEnglishMeaning: 'The project should already have documentary backup for key downstream pricing.',
    whyItMatters: 'This is a major support clause for open-book pricing and change proof, especially when redesign or review comments drive commercial impacts.',
    triggerConditions: ['Need pricing backup', 'Change pricing support request', 'Designer cost substantiation'],
    linkedIssueTypes: ['compensation-risk', 'owner-driven-change', 'mixed-issue'],
    linkedDeadlineTypes: ['pricing_support_request_due'],
    linkedOutputTypes: OUTPUTS,
    perspectiveNotes: notes(
      'Gather designer and builder backup early if a change issue is developing.',
      'This keeps downstream pricing support inside the live commercial file.',
      'It is a strong basis for asking for subcontractor and consultant backup.',
      'Use it when testing whether pricing support is complete enough to trust.'
    ),
    confidence: 'High',
    tags: ['pricing', 'subcontractor', 'lead-designer'],
  },
  {
    slug: 'open-book-pricing-verification',
    sectionRef: 'Exhibit G §2(ii)(c)-(d)',
    pageRef: 'Exhibit G p.G-4 / PDF p.285',
    title: 'Open-book pricing and original-cost verification',
    clauseFamily: 'pricing_support',
    clauseSubtype: 'open_book_pricing',
    excerpt: 'Change-related cost determinations are negotiated on an Open-Book Basis and are subject to verification against Escrowed Proposal Documents and other original pricing information, including Section 17.11 pricing support.',
    plainEnglishMeaning: 'Change pricing is supposed to be transparent and testable against original pricing support.',
    whyItMatters: 'This shapes how a commercial response should ask for pricing support and how a change proposal should be documented.',
    triggerConditions: ['Open-book negotiation', 'Verification against original pricing', 'Need cost transparency'],
    linkedIssueTypes: ['compensation-risk', 'owner-driven-change', 'mixed-issue'],
    linkedDeadlineTypes: ['pricing_support_request_due'],
    linkedOutputTypes: OUTPUTS,
    perspectiveNotes: notes(
      'Expect pricing assertions to be tested against original estimate support.',
      'Transparent build-ups are more credible than lump-sum demands.',
      'This is the right clause for a measured open-book change proposal posture.',
      'Use it when pushing for auditable cost support instead of broad assumptions.'
    ),
    confidence: 'High',
    tags: ['open-book', 'verification', 'original-pricing'],
  },
];

export function buildLadotDemoClauses(projectId: string, documentId: string, now = new Date().toISOString()): ClauseRecord[] {
  return CALCASIEU_DEMO_SEED.map((clause) => ({
    ...clause,
    id: `${projectId}:clause:${clause.slug}`,
    projectId,
    documentId,
    documentType: 'contract',
    createdAt: now,
    updatedAt: now,
  }));
}
